# MACHINE LEARNING SERIES
<b> Deep Learning and Mathematical Models are branches of Machine Learning </b>

# REGRESSION

## Linear Regression Multi Variable
### Multivariate Regression 

<code>y = m1X1 + m2X2 + m3X3 + b</code>

In [33]:
df = pd.read_csv("homeprice.csv")

In [34]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  680000
4  4000      5.0    8  725000

### Performing data preprocessing on the missing value

In [35]:
import math

<b> using the median value will be the safest </b>

In [36]:
median_bedroom = math.floor(df.bedroom.median())

In [37]:
median_bedroom

3

<b>filling the missing value with the median</b>

In [38]:
df.bedroom = df.bedroom.fillna(median_bedroom)

In [39]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  680000
4  4000      5.0    8  725000

In [40]:
reg = linear_model.LinearRegression()

In [41]:
reg.fit(df[["area", "bedroom", "age"]], df.price)

LinearRegression()

In [42]:
reg.fit(df[["area", "bedroom", "age"]], df.price)

LinearRegression()

In [43]:
#predict no_1)  3000 sqr ft, 3 bedroom, 40 year old
#        no_2)  2500 sqr ft, 4 bedroom, 5 year old

In [44]:
no_1 = reg.predict([[3000,3,40]])
no_1

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([597200.])

In [45]:
no_2 = reg.predict([[2500,4,5]])
no_2

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([506812.5])

In [46]:
reg.coef_

array([  143.625, -6762.5  ,   337.5  ])

In [47]:
reg.intercept_

173112.50000000012

In [48]:
y = 143.625*2500 + (-6762.5)*4 + 337.5*5 + 173112.50000000012
y

506812.5000000001

### Exercise

There is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

<b>2 yr experience, 9 test score, 6 interview score</b>

<b>12 yr experience, 10 test score, 10 interview score</b>

### Answer

53713.86 and 93747.79

In [50]:
from word2number import w2n

In [51]:
df = pd.read_csv("hiring.csv")

In [52]:
#fill the nan with 0 in the experience column
df.experience = df.experience.fillna("Zero")

In [53]:
import math

In [54]:
#fill the nan with the mean in the test_score column

md = math.floor(df["test_score(out of 10)"].mean())

In [55]:
md

7

In [56]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(md)

In [57]:
arr = np.array(df.experience)

In [58]:
arr

array(['Zero', 'Zero', 'five', 'two', 'seven', 'three', 'ten', 'eleven'],
      dtype=object)

In [59]:
#coverting word to number
value = []
for i in arr:
    value.append(w2n.word_to_num(i))
df.experience = value

#or

#d.experience = d.experience.apply(w2n.word_to_num)

In [60]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [61]:
from sklearn import linear_model

In [62]:
reg = linear_model.LinearRegression()

In [63]:
reg.fit(df[["experience","test_score(out of 10)", "interview_score(out of 10)"]], df[["salary($)"]])

LinearRegression()

In [64]:
#no_1
#2 yr experience, 9 test score, 6 interview score
reg.predict([[2,9,6]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53713.86677124]])

In [65]:
#no_2
#12 yr experience, 10 test score, 10 interview score
reg.predict([[12,10,10]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[93747.79628651]])