# K Fold Cross Validation

In knowing the type of machine learning classifier to use when solving a problem we use K fold cross validation technique, it allows us to evaluate a model performance.

In K-fold cross validation technique, we split the datasets into different fold, and perform the training and testing techniques iteratively and note the score and average them. This is good because you are training and testing the model with different set of data then taking the average score.


In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [15]:
#Using logistic regression
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [16]:
#Using SVM
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

In [18]:
#Using RandomForest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9851851851851852

In [25]:
#Using K-Forld API to test for the accuracy of the model
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
for train_index, test_index in kf.split([2,3,4,5,6,7,8,9]):
    print(train_index, test_index)


[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]


In [26]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [27]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [28]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9907407407407407

In [29]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9814814814814815

In [50]:
#Using stratifield k-fold
score_l = []
score_svm = []
score_rf = []

from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    score_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
print(f"LogisticRegression scores: {score_l} \nSVM scores: {score_svm} \nRandom Forest score {score_rf}")    

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

LogisticRegression scores: [0.9215358931552587, 0.9415692821368948, 0.9165275459098498] 
SVM scores: [0.9649415692821369, 0.9799666110183639, 0.9649415692821369] 
Random Forest score [0.9348914858096828, 0.9582637729549248, 0.9248747913188647]


In [44]:
score_l

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [45]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [48]:
score_rf

[0.9181969949916527, 0.9499165275459098, 0.9148580968280468]

In [51]:
#Using cross validation score method

from sklearn.model_selection import cross_val_score

In [56]:
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=3)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92153589, 0.94156928, 0.91652755])

In [55]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [60]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=3)

array([0.93989983, 0.94824708, 0.92821369])

<b>Exercise</b>:
<br>
With the Iris dataset, use cross validation score to know the model with the best accuracy

In [61]:
from sklearn.datasets import load_iris

iris = load_iris()

In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [63]:
from sklearn.model_selection import cross_val_predict

In [64]:
cross_val_score(LogisticRegression(), iris.data, iris.target, cv=4)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.97368421, 0.97368421, 0.94594595, 1.        ])

In [65]:
cross_val_score(SVC(), iris.data, iris.target, cv=4)

array([0.97368421, 1.        , 0.94594595, 0.97297297])

In [66]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=4)

array([0.97368421, 0.94736842, 0.91891892, 1.        ])